server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #,http://localhost:8766/eureka/

spring:
  application:
    name: eureka-client1
  cloud:
      config:
        label: master
        uri: http://localhost:8888/
        profile: dev