spring:
  cloud:
    config:
      label: master
      server:
        native:
          search-locations: classpath:/config
          add-label-locations: true
#        git:
#          uri: https://github.com/FengCaiHappy/cloud-config.git
#          username:
#          password:
#          timeout: 10
  profiles:
    active: native
  application:
    name: cloud-config

server:
  port: 8888

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8766/eureka/