server:
  port: 8766

spring:
  application:
    name: cloud-server

eureka:
  instance:
    hostname: cloud-server2
    appname: cloud-server
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://cloud-server1:8761/eureka/